#!/usr/bin/env bash
set -euo pipefail

mkdir -p static/knowledge

cat > static/knowledge/portfolio-knowledge.txt <<'EOF'
# Abbas Portfolio Knowledge

This file is automatically generated from the portfolio repository.

Generated from markdown files inside the content folder.
EOF

process_markdown() {
  local file="$1"
  perl .github/scripts/process-markdown.pl "$file"
}

find content -type f -name "*.md" | sort | while IFS= read -r file; do
  process_markdown "$file" >> static/knowledge/portfolio-knowledge.txt
done